# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: r
r:
  - devel
sudo: false
cache: packages
r_github_packages:
 - robjhyndman/forecast
 - robjhyndman/tsfeatures

